name: Terraform + Docker Workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # AWS Step
      - name: AWS Login
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
             aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
             aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
             aws-region: us-east-1

      # Terraform Step
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      # Docker Step
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t my-combined-image:latest .

      - name: Save Docker Image
        run: docker save my-combined-image:latest -o my-combined-image.tar

      - name: Upload as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: my-combined-image.tar
