name: Docker Hub Login Check

on:
  workflow_dispatch:

jobs:
  docker-login-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ✅ Use this action to login to Docker Hub using secrets
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ✅ Check login status
      - name: Check Login Status
        run: |
          if docker info | grep -i "Username:"; then
            echo "✅ Docker login successful!"
          else
            echo "❌ Docker login failed!"
            exit 1
          fi

      # ✅ Optional: Build Docker image (make sure Dockerfile exists in repo)
      - name: Build Docker Image
        run: |
          docker build -t test-login-image .
