name: Pull Docker Image and Upload Artifact

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  pull-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Docker Image from Docker Hub
        run: docker pull nginx:latest  # you can replace with your desired image

      - name: Save Docker Image as tar
        run: docker save nginx:latest -o pulled-image.tar

      - name: Upload Docker Image as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pulled-docker-image
          path: pulled-image.tar
